name:                Sleazy
version:             0.1.0.0
github:              "eriksvedang/Sleazy"
license:             BSD3
author:              "Erik Svedäng"
maintainer:          "erik.svedang@gmail.com"
copyright:           "Erik Svedäng"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            General

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/eriksvedang/Sleazy#readme>

dependencies:
- base >= 4.7 && < 5
- text
- containers

library:
  source-dirs: src

executables:
  Sleazy-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Sleazy

tests:
  Sleazy-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - Sleazy
